name: Example report - PR

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR to run'
        required: true
        type: string

env:
  PER_PAGE: 20

jobs:
  get-environment:
    name: Get Environment
    runs-on: ubuntu-latest
    outputs:
      pages: ${{ steps.env.outputs.pages }}
      gitref: ${{ steps.env.outputs.gitref }}
      date: ${{ steps.env.outputs.date }}
      pixeleagle_project: ${{ steps.env.outputs.pixeleagle_project }}
    steps:
      - name: Checkout Bevy main branch
        uses: actions/checkout@v4
        with:
          repository: 'bevyengine/bevy'
      - name: Switch to PR
        run: |
          git fetch origin pull/${{ inputs.pr }}/head:pr-${{ inputs.pr }}
          git switch pr-${{ inputs.pr }}
      - name: Get Environment
        id: env
        run: |
          example_count=`cat Cargo.toml | grep '\[\[example\]\]' | wc -l`
          page_count=$((example_count / ${{ env.PER_PAGE }} + 1))

          echo "gitref=`git rev-parse HEAD`" >> $GITHUB_OUTPUT
          echo "date=`date +%Y%m%d%H%M`" >> $GITHUB_OUTPUT
          echo "pages=`python -c \"import json; print(json.dumps([i for i in range($page_count)]))\"`" >> $GITHUB_OUTPUT
          echo "pixeleagle_project=B25A040A-A980-4602-B90C-D480AB84076D" >> $GITHUB_OUTPUT

  native-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-mobile.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "PR-${{ inputs.pr }}"
      repository: "bevyengine/bevy"
    secrets: inherit
        
  mobile-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-mobile.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "PR-${{ inputs.pr }}"
      repository: "bevyengine/bevy"
    secrets: inherit

  wasm-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-wasm.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "PR-${{ inputs.pr }}"
      repository: "bevyengine/bevy"
    secrets: inherit
