name: Workflow - Tests on wasm

on:
  workflow_call:
    inputs:
      gitref:
        required: true
        type: string
      pixeleagle_project:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  wasm-run:
    runs-on: ${{ matrix.runner}}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: "macos-14"
            browser: "chromium"
            api: "webgl2"
          - runner: "macos-14"
            browser: "chromium"
            api: "webgpu"
          - runner: "macos-14"
            browser: "webkit"
            api: "webgl2"
          - runner: "macos-14"
            browser: "webkit"
            api: "webgpu"
          - runner: "macos-14"
            browser: "firefox"
            api: "webgl2"
          - runner: "macos-14"
            browser: "firefox"
            api: "webgpu"
          - runner: "ubuntu-latest"
            browser: "firefox"
            api: "webgl2"
          - runner: "ubuntu-latest"
            browser: "firefox"
            api: "webgpu"
          - runner: "ubuntu-latest"
            browser: "chromium"
            api: "webgl2"
          - runner: "ubuntu-latest"
            browser: "chromium"
            api: "webgpu"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'bevyengine/bevy'
          ref: ${{ inputs.gitref }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown  
  
      - name: install xvfb, llvmpipe and lavapipe
        if: runner.os == 'linux'
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/turtle -y
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: Install wasm-bindgen
        run: cargo install --force wasm-bindgen-cli

      - name: Setup playwright
        run: |
          cd .github/start-wasm-example
          npm install
          # update playwright to get the latest browsers
          npm install -D @playwright/test@latest
          npx playwright install --with-deps
          cd ../..

      - name: Run examples
        if: runner.os == 'linux'
        shell: bash
        run: |
          # start a webserver
          python3 -m http.server --directory examples/wasm &

          xvfb-run cargo run -p build-wasm-example -- --browsers ${{ matrix.browser }} --api ${{ matrix.api }} --frames 25 --test lighting

      - name: Run examples
        if: runner.os == 'macos'
        shell: bash
        run: |
          # start a webserver
          python3 -m http.server --directory examples/wasm &

          cargo run -p build-wasm-example -- --browsers ${{ matrix.browser }} --api ${{ matrix.api }} --frames 25 --test lighting

      - name: Save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-wasm-${{ matrix.browser }}-${{ matrix.api }}-${{ runner.os }}
          path: .github/start-wasm-example/screenshot-*.png
    
      - name: Send to Pixel Eagle
        run: |
          run=`curl https://pixel-eagle.vleue.com/${{ inputs.pixeleagle_project }}/runs -H 'Content-Type: application/json' -d '{"api":"${{ matrix.api }}", "browser": "${{ matrix.browser }}", "os":"wasm", "gitref": "${{ inputs.gitref }}", "branch": "${{ inputs.branch }}"}' | jq '.id'`
            
          SAVEIFS=$IFS
          
          IFS=$'\n'

          cd .github/start-wasm-example

          # Build a json array of screenshots and their hashes
          hashes='[';
          for screenshot in $(find . -type f -maxdepth 1 -name "*.png");
          do
            name=${screenshot:2}
            echo $name
            hash=`shasum -a 256 $screenshot | awk '{print $1}'`
            hashes="$hashes [\"$name\",\"$hash\"],"
          done
          hashes=`echo $hashes | rev | cut -c 2- | rev`
          hashes="$hashes]"
          
          IFS=$SAVEIFS          

          # Upload screenshots with unknown hashes
          curl https://pixel-eagle.vleue.com/${{ inputs.pixeleagle_project }}/runs/$run/hashes -H 'Content-Type: application/json' -d "$hashes" | jq '.[]|[.name] | @tsv' |
            while IFS=$'\t' read -r name; do
              name=`echo $name | tr -d '"'`
              echo "Uploading $name"
              curl https://pixel-eagle.vleue.com/${{ inputs.pixeleagle_project }}/runs/$run/screenshots -F "data=@./$name" -F "screenshot=$name"
              echo
            done
          
          IFS=$SAVEIFS
  