name: Workflow - Tests on wasm

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      gitref:
        required: true
        type: string
      pixeleagle_project:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  wasm-run:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: "macos-14"
            browser: "chromium"
            api: "webgpu"
          - runner: "ubuntu-latest"
            browser: "firefox"
            api: "webgl2"
          # works, but text is buggy
          # - runner: "ubuntu-latest"
          #   browser: "chromium"
          #   api: "webgl2"
          # doesn't work but should, don't know why
          # - runner: "macos-14"
          #   browser: "chromium"
          #   api: "webgl2"
          # - runner: "macos-14"
          #   browser: "webkit"
          #   api: "webgl2"
          # - runner: "macos-14"
          #   browser: "firefox"
          #   api: "webgl2"
          # doesn't work for now, that's expected
          # - runner: "macos-14"
          #   browser: "webkit"
          #   api: "webgpu"
          # - runner: "macos-14"
          #   browser: "firefox"
          #   api: "webgpu"
          # - runner: "ubuntu-latest"
          #   browser: "firefox"
          #   api: "webgpu"
          # - runner: "ubuntu-latest"
          #   browser: "chromium"
          #   api: "webgpu"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.gitref }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown  
  
      - name: install xvfb, llvmpipe and lavapipe
        if: runner.os == 'linux'
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/turtle -y || FAILED=true
          # retry as it sometimes timeout
          if [ $FAILED ]; then
            sleep 5
            sudo add-apt-repository ppa:kisak/turtle -y || FAILED=true
            if [ $FAILED ]; then
                  sleep 5
                  sudo add-apt-repository ppa:kisak/turtle -y
            fi
          fi
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
